"""Add mpesa_code column to catch table

Revision ID: e600f7df4b31
Revises: 
Create Date: 2025-06-09 04:28:55.503143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e600f7df4b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=15), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=13), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mpesa_code')

    with op.batch_alter_table('catch', schema=None) as batch_op:
        batch_op.drop_column('mpesa_code')

    # ### end Alembic commands ###
